'use client'
import Link from 'next/link'
import { Bell, Bookmark, CircleCheck, Flag, LogIn, Search, ShieldCheck, Sparkles, UserRound } from 'lucide-react'
import { useRouter } from 'next/navigation'
import { useEffect, useMemo, useState } from 'react'
import { Composer } from './Composer'
import { Identity } from './Identity'
import { PostCard } from './PostCard'
import { Timeline } from './Timeline'

export function HomeScreen(){return <><header className="page-header"><h1 className="page-title">المساحة العامة</h1><p className="page-description">الأحدث أولًا. بلا خوارزمية ترتيب.</p></header><Timeline/></>}

export function ScreenRouter({slug}){
  const key=slug.join('/')
  if(key==='login') return <AuthScreen mode="login"/>
  if(key==='register') return <AuthScreen mode="register"/>
  if(key==='write') return <Composer/>
  if(key==='first-post') return <Composer firstPost/>
  if(key==='search') return <SearchScreen/>
  if(key==='me') return <MeScreen/>
  if(key==='notifications') return <NotificationsScreen/>
  if(key==='bookmarks') return <BookmarksScreen/>
  if(key==='privacy') return <PrivacyScreen/>
  if(key==='admin/reports') return <AdminReportsScreen/>
  if(slug[0]==='u'&&slug[1]) return <UserScreen code={slug[1]}/>
  if(slug[0]==='post'&&slug[1]) return <PostScreen id={slug[1]}/>
  if(slug[0]==='report'&&slug[1]==='post'&&slug[2]) return <ReportScreen id={slug[2]}/>
  return <NotFound/>
}

function AuthScreen({mode}){
  const router=useRouter(); const login=mode==='login'; const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [confirm,setConfirm]=useState(false)
  async function submit(e){e.preventDefault();setError('');setBusy(true);const fd=new FormData(e.currentTarget);try{const res=await fetch(`/api/auth/${login?'login':'register'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:fd.get('email'),password:fd.get('password')})});const data=await res.json();if(!res.ok)throw new Error(data.error||'تعذر إكمال العملية');if(data.requiresEmailConfirmation){setConfirm(true);return}router.push(login?'/':'/first-post');router.refresh()}catch(e){setError(e.message)}finally{setBusy(false)}}
  if(confirm)return <div className="auth-wrap center"><div className="panel" style={{padding:28}}><CircleCheck size={38} className=""/><h1 className="auth-title mt16">تحقق من بريدك</h1><p className="auth-sub">أرسلنا رابط تأكيد إلى بريدك. بعد التأكيد، ارجع وسجّل الدخول.</p><Link href="/login" className="primary-button full mt20">الذهاب إلى الدخول</Link></div></div>
  return <div className="auth-wrap"><div className="auth-head"><div className="auth-icon">{login?<LogIn size={21}/>:<Sparkles size={21}/>}</div><h1 className="auth-title">{login?'مرحبًا بعودتك':'أنشئ هويتك'}</h1><p className="auth-sub">{login?'ادخل إلى هويتك وكلماتك.':'سنمنحك كودًا ولونًا ثابتين؛ لا اسم عرض ولا صورة شخصية.'}</p></div><form className="panel auth-form" onSubmit={submit}><label className="label">البريد الإلكتروني<input className="form-control" type="email" name="email" autoComplete="email" required dir="ltr" placeholder="name@example.com"/></label><label className="label">كلمة المرور<input className="form-control" type="password" name="password" autoComplete={login?'current-password':'new-password'} minLength={login?undefined:8} maxLength={128} required dir="ltr" placeholder="••••••••"/></label>{error&&<p className="status-message error">{error}</p>}<button className="primary-button full" disabled={busy}>{busy?'جارِ التنفيذ…':login?'تسجيل الدخول':'إنشاء الحساب'}</button></form><p className="center muted small mt20">{login?'ليس لديك حساب؟ ':'لديك حساب؟ '}<Link href={login?'/register':'/login'} style={{textDecoration:'underline'}}>{login?'أنشئ هويتك':'تسجيل الدخول'}</Link></p></div>
}

function SearchScreen(){const[q,setQ]=useState('');const[posts,setPosts]=useState([]);const[users,setUsers]=useState([]);const[busy,setBusy]=useState(false);const[done,setDone]=useState(false);async function run(e){e?.preventDefault();if(!q.trim())return;setBusy(true);try{const r=await fetch(`/api/search?q=${encodeURIComponent(q.trim())}`,{cache:'no-store'});const d=await r.json();setPosts(d.posts||[]);setUsers(d.users||[]);setDone(true)}finally{setBusy(false)}}return <><header className="page-header"><div className="page-title-row"><Search size={20}/><h1 className="page-title">بحث</h1></div><p className="page-description">ابحث عن كلمات عامة أو كود هوية.</p></header><form className="search-box row" onSubmit={run}><input className="form-control" value={q} onChange={e=>setQ(e.target.value)} maxLength={120} placeholder="ابحث…"/><button className="primary-button" disabled={busy||!q.trim()}>{busy?'…':'بحث'}</button></form>{users.length>0&&<><div className="section-title">الهويات</div>{users.map(u=><div className="list-row" key={u.publicCode}><Identity code={u.publicCode} color={u.identityColor}/><Link className="small muted" href={`/u/${u.publicCode}`}>عرض</Link></div>)}</>}{posts.length>0&&<><div className="section-title">المنشورات</div>{posts.map(p=><PostCard key={p.id} post={p}/>)}</>}{done&&!users.length&&!posts.length&&<div className="empty-state"><p>لا توجد نتائج.</p></div>}</>}

function MeScreen(){const router=useRouter();const[user,setUser]=useState(undefined);const[count,setCount]=useState(null);const[following,setFollowing]=useState([]);useEffect(()=>{(async()=>{const m=await fetch('/api/auth/me',{cache:'no-store'});const md=m.ok?await m.json():{user:null};setUser(md.user||null);if(md.user){const[a,b]=await Promise.all([fetch('/api/me/followers-count',{cache:'no-store'}),fetch('/api/me/following',{cache:'no-store'})]);if(a.ok)setCount((await a.json()).count);if(b.ok)setFollowing((await b.json()).items||[])}})()},[]);async function logout(){await fetch('/api/auth/logout',{method:'POST'});router.push('/');router.refresh()}if(user===undefined)return <div className="screen-pad"><div className="skeleton"/></div>;if(user===null)return <div className="empty-state"><div><p>سجّل الدخول لرؤية حسابك.</p><Link href="/login" className="primary-button mt16">تسجيل الدخول</Link></div></div>;return <><header className="page-header"><h1 className="page-title">حسابي</h1><p className="page-description">هويتك الخاصة وإعدادات علاقاتك العامة.</p></header><section className="profile-hero"><Identity code={user.publicCode} color={user.identityColor} large/><div className="stat-grid"><div className="panel stat"><span className="small muted">الأشخاص المهتمون بما تكتب</span><strong>{count??'—'}</strong></div><div className="panel stat"><span className="small muted">خاص بك فقط</span><p className="small mt12">لا نعرض عدد متابَعاتك للآخرين.</p></div></div><div className="row wrap mt20"><Link href={`/u/${user.publicCode}`} className="secondary-button">صفحة كتاباتي</Link><Link href="/bookmarks" className="secondary-button"><Bookmark size={15}/>المحفوظات</Link><Link href="/privacy" className="secondary-button">الخصوصية</Link><button onClick={logout} className="danger-button">تسجيل الخروج</button></div></section><div className="section-title">الأكواد التي أتابعها</div>{following.length?following.map(x=><div key={x.publicCode} className="list-row"><Identity code={x.publicCode} color={x.identityColor}/><Link href={`/u/${x.publicCode}`} className="small muted">عرض</Link></div>):<div className="empty-state"><p>لم تتابع أي كود بعد.</p></div>}</>}

function UserScreen({code}){const[user,setUser]=useState(undefined);const[posts,setPosts]=useState([]);const[busy,setBusy]=useState('');useEffect(()=>{(async()=>{const [u,p]=await Promise.all([fetch(`/api/users/${encodeURIComponent(code)}`,{cache:'no-store'}),fetch(`/api/posts?author=${encodeURIComponent(code)}`,{cache:'no-store'})]);setUser(u.ok?(await u.json()).user:null);if(p.ok)setPosts((await p.json()).items||[])})()},[code]);async function relation(kind,enabled){if(busy)return;setBusy(kind);const r=await fetch(`/api/users/${code}/relation`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,enabled})});if(r.status===401){location.href='/login';return}if(r.ok)setUser(u=>({...u,[kind==='follow'?'viewerIsFollowing':kind==='mute'?'viewerHasMuted':'viewerHasBlocked']:enabled}));setBusy('')}if(user===undefined)return <div className="screen-pad"><div className="skeleton"/></div>;if(!user)return <NotFound/>;return <><section className="profile-hero"><Identity code={user.publicCode} color={user.identityColor} large/>{user.status&&<p className="profile-status">{user.status}</p>}{user.bio&&<p className="profile-bio">{user.bio}</p>}<p className="profile-meta">انضم في {new Intl.DateTimeFormat('ar',{dateStyle:'medium'}).format(new Date(user.createdAt))}</p>{!user.isSelf&&<div className="row wrap mt20"><button className="primary-button" disabled={busy==='follow'} onClick={()=>relation('follow',!user.viewerIsFollowing)}>{user.viewerIsFollowing?'إلغاء المتابعة':'متابعة'}</button><button className="secondary-button" disabled={busy==='mute'} onClick={()=>relation('mute',!user.viewerHasMuted)}>{user.viewerHasMuted?'إلغاء الكتم':'كتم'}</button><button className="danger-button" disabled={busy==='block'} onClick={()=>relation('block',!user.viewerHasBlocked)}>{user.viewerHasBlocked?'إلغاء الحظر':'حظر'}</button></div>}</section><div className="section-title">الكتابات</div>{posts.length?posts.map(p=><PostCard key={p.id} post={p}/>):<div className="empty-state"><p>لا توجد منشورات.</p></div>}</>}

function PostScreen({id}){const[post,setPost]=useState(undefined);const[comments,setComments]=useState([]);const[body,setBody]=useState('');const[busy,setBusy]=useState(false);async function load(){const r=await fetch(`/api/posts/${id}`,{cache:'no-store'});if(!r.ok){setPost(null);return}const d=await r.json();setPost(d.post);setComments(d.comments||[])}useEffect(()=>{load()},[id]);async function comment(e){e.preventDefault();if(!body.trim())return;setBusy(true);const r=await fetch(`/api/posts/${id}/comments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body})});if(r.status===401){location.href='/login';return}if(r.ok){setBody('');await load()}setBusy(false)}if(post===undefined)return <div className="screen-pad"><div className="skeleton"/></div>;if(!post)return <NotFound/>;return <><PostCard post={post}/><form className="comment-form" onSubmit={comment}><textarea className="form-control" maxLength={2000} value={body} onChange={e=>setBody(e.target.value)} placeholder="اكتب تعليقًا…"/><div className="row between"><span className="tiny subtle" dir="ltr">{body.length} / 2000</span><button className="primary-button" disabled={busy||!body.trim()}>{busy?'جارِ الإرسال…':'تعليق'}</button></div></form><div className="section-title">التعليقات</div>{comments.length?comments.map(c=><article className="comment" key={c.id}><div className="row between"><Identity code={c.authorCode} color={c.authorColor}/><time className="tiny subtle">{new Intl.DateTimeFormat('ar',{dateStyle:'medium',timeStyle:'short'}).format(new Date(c.createdAt))}</time></div><p className="comment-body">{c.body}</p></article>):<div className="empty-state"><p>لا توجد تعليقات بعد.</p></div>}</>}

function NotificationsScreen(){const[items,setItems]=useState(undefined);async function load(){const r=await fetch('/api/notifications',{cache:'no-store'});if(r.status===401){setItems(null);return}const d=await r.json();setItems(d.items||[]);if((d.items||[]).some(x=>!x.readAt))await fetch('/api/notifications',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:(d.items||[]).filter(x=>!x.readAt).map(x=>x.id)})})}useEffect(()=>{load()},[]);if(items===undefined)return <div className="screen-pad"><div className="skeleton"/></div>;if(items===null)return <div className="empty-state"><Link href="/login" className="primary-button">تسجيل الدخول</Link></div>;return <><header className="page-header"><div className="page-title-row"><Bell size={20}/><h1 className="page-title">الإشعارات</h1></div><p className="page-description">التفاعلات والردود المرتبطة بك.</p></header>{items.length?items.map(n=><Link href={`/post/${n.postId}`} className={`notification${n.readAt?'':' unread'}`} key={n.id}><span className="notification-icon">{n.kind==='like'?'♥':'↩'}</span><div className="notification-main"><p><Identity code={n.actorCode} color={n.actorColor}/> {n.kind==='like'?'أعجب بمنشورك':'رد على منشورك'}</p><time>{new Intl.DateTimeFormat('ar',{dateStyle:'medium',timeStyle:'short'}).format(new Date(n.createdAt))}</time></div></Link>):<div className="empty-state"><p>لا توجد إشعارات.</p></div>}</>}

function BookmarksScreen(){return <><header className="page-header"><div className="page-title-row"><Bookmark size={20}/><h1 className="page-title">المحفوظات</h1></div><p className="page-description">منشورات محفوظة لك فقط.</p></header><Timeline endpoint="/api/bookmarks" empty="لا توجد منشورات محفوظة."/></>}

function PrivacyScreen(){const[items,setItems]=useState(undefined);async function load(){const r=await fetch('/api/privacy',{cache:'no-store'});setItems(r.ok?(await r.json()).items:null)}useEffect(()=>{load()},[]);async function undo(kind,code){await fetch(`/api/users/${code}/relation`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,enabled:false})});await load()}if(items===undefined)return <div className="screen-pad"><div className="skeleton"/></div>;if(items===null)return <div className="empty-state"><Link href="/login" className="primary-button">تسجيل الدخول</Link></div>;return <><header className="page-header"><h1 className="page-title">الخصوصية</h1><p className="page-description">إدارة الحسابات المكتومة والمحظورة.</p></header>{items.length?items.map((x,i)=><div className="list-row" key={`${x.kind}-${x.publicCode}-${i}`}><div><Identity code={x.publicCode} color={x.identityColor}/><div className="tiny muted mt8">{x.kind==='mute'?'مكتوم':'محظور'}</div></div><button className="secondary-button" onClick={()=>undo(x.kind==='mute'?'mute':'block',x.publicCode)}>إلغاء</button></div>):<div className="empty-state"><p>لا توجد علاقات خصوصية حاليًا.</p></div>}</>}

function ReportScreen({id}){const router=useRouter();const[error,setError]=useState('');const[busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);const r=await fetch('/api/reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({targetType:'post',targetId:id,reason:f.get('reason'),description:f.get('description')||null})});if(r.status===401){router.push('/login');return}if(r.ok)router.back();else setError('تعذر إرسال البلاغ.');setBusy(false)}return <><header className="page-header"><div className="page-title-row"><Flag size={20}/><h1 className="page-title">إبلاغ عن منشور</h1></div><p className="page-description">البلاغات خاصة ويطّلع عليها فريق الإشراف فقط.</p></header><form className="screen-pad stack" onSubmit={submit}><label className="label">السبب<select name="reason" className="form-control" defaultValue="spam"><option value="spam">محتوى مزعج أو مكرر</option><option value="harassment">مضايقة</option><option value="hate">خطاب كراهية</option><option value="threat">تهديد</option><option value="sexual">محتوى جنسي</option><option value="illegal">محتوى غير قانوني</option><option value="other">سبب آخر</option></select></label><label className="label">تفاصيل إضافية<textarea name="description" maxLength={1000} className="form-control" style={{minHeight:128}} placeholder="اختياري"/></label>{error&&<p className="status-message error">{error}</p>}<div className="row"><button className="primary-button" disabled={busy}>{busy?'جارِ الإرسال…':'إرسال البلاغ'}</button><button className="secondary-button" type="button" onClick={()=>router.back()}>إلغاء</button></div></form></>}

function AdminReportsScreen(){const[items,setItems]=useState(undefined);const[error,setError]=useState('');async function load(){const r=await fetch('/api/admin/reports',{cache:'no-store'});if(!r.ok){setError(r.status===403?'غير مصرح لك.':'تعذر تحميل البلاغات.');setItems([]);return}setItems((await r.json()).items||[])}useEffect(()=>{load()},[]);async function act(id,action){const r=await fetch(`/api/admin/reports/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});if(r.ok)await load()}if(items===undefined)return <div className="screen-pad"><div className="skeleton"/></div>;return <><header className="page-header"><div className="page-title-row"><ShieldCheck size={20}/><h1 className="page-title">البلاغات</h1></div></header>{error&&<div className="screen-pad"><p className="status-message error">{error}</p></div>}{items.map(x=><article className="admin-card" key={x.id}><div className="small muted">{x.targetType} · {x.reason} · {x.status}</div><div className="mono tiny mt8">{x.targetId}</div>{x.description&&<p>{x.description}</p>}<div className="row wrap mt16">{[['delete-content','حذف المحتوى'],['suspend-author','تعليق الحساب'],['ban-author','حظر الحساب'],['resolve','حل'],['dismiss','رفض البلاغ']].map(([a,l])=><button key={a} className="secondary-button" onClick={()=>act(x.id,a)}>{l}</button>)}</div></article>)}{!error&&!items.length&&<div className="empty-state"><p>لا توجد بلاغات.</p></div>}</>}

function NotFound(){return <div className="empty-state"><div><UserRound size={28}/><h1>الصفحة غير موجودة</h1><p>ربما تغيّر الرابط أو حُذف المحتوى.</p><Link href="/" className="primary-button mt16">العودة للرئيسية</Link></div></div>}
